[general]
import = [
  # "~/.config/alacritty/themes/catppuccin-frappe.toml",
  # "~/.config/alacritty/themes/catppuccin-latte.toml",
  # "~/.config/alacritty/themes/catppuccin-macchiato.toml",
  # "~/.config/alacritty/themes/catppuccin-mocha.toml",
  # "~/.config/alacritty/themes/dracula.toml",
  "~/.config/alacritty/themes/rose-pine-dawn.toml",
  # "~/.config/alacritty/themes/rose-pine-moon.toml",
  # "~/.config/alacritty/themes/rose-pine.toml"
]

[window]
padding = { x = 8, y = 8 }
decorations = "Full"
opacity = 0.95

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
size = 12
